-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 29, 2024 at 03:27 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.0.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `web_resep`
--

-- --------------------------------------------------------

--
-- Table structure for table `bookmarks`
--

CREATE TABLE `bookmarks` (
  `user_id` int(11) NOT NULL,
  `resep_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `bookmarks`
--

INSERT INTO `bookmarks` (`user_id`, `resep_id`) VALUES
(7, 1),
(6, 2),
(6, 1),
(4, 1),
(4, 71);

-- --------------------------------------------------------

--
-- Table structure for table `resep`
--

CREATE TABLE `resep` (
  `resep_id` int(11) NOT NULL,
  `nama_resep` varchar(255) NOT NULL,
  `deskripsi_resep` text NOT NULL,
  `bahan` text NOT NULL,
  `gambar` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `resep`
--

INSERT INTO `resep` (`resep_id`, `nama_resep`, `deskripsi_resep`, `bahan`, `gambar`) VALUES
(1, 'test edit', 'test edit', 'test edit', 'gambar/ayamgoreng38.jpeg'),
(2, 'test edit 2', 'test edit 2', 'test edit 2', 'gambar/ayamgoreng41.jpeg'),
(4, 'Ayam Goreng', 'Ayam Goreng adalah hidangan tradisional Indonesia yang sangat populer dan menjadi salah satu kuliner yang dicintai di seluruh nusantara. Hidangan ini terdiri dari potongan ayam yang digoreng hingga kulitnya menjadi renyah dan berwarna kecoklatan. Sebelum digoreng, ayam biasanya direndam atau diremas dalam bumbu yang dapat mencakup bawang putih, ketumbar, garam, dan merica untuk memberikan cita rasa yang khas. Metode ini memberikan ayam goreng karakteristiknya yang gurih dan berbumbu. Ayam goreng sering dihidangkan bersama nasi putih dan sambal sebagai pelengkap. Hidangan ini bisa ditemui di warung-warung kaki lima, restoran, hingga rumah makan di seluruh Indonesia. Karena kelezatannya, ayam goreng juga sering dijadikan hidangan dalam acara-acara khusus, pesta, atau acara keluarga.', 'Bahan-bahan:\n1 kg Ayam, cuci bersih dan potong sesuai selera\n2 Bonggol bawang putih\n1 butir telur ayam\n3 sdm tepung maizena\n1/2 sdt garam\n1/4 sdt kaldu bubuk\nSecukupnya minyak goreng untuk menggoreng\nBumbu Halus:\n6 siung Bawang putih\n5 siung Bawang Merah\n1 sdt ketumbar bubuk\n1/2 sdt merica bubuk\n1 sdt kunyit bubuk\n1,5 ruas jari jahe\nCara Membuat:\nLangkah 1\nCuci ayam hingga bersih kemudian tiriskan masukan bumbu halus, garam, kaldu bubuk, tepung maizena & telur..aduk hingga tercampur rata.\nLangkah 2\nDiamkan kurang lebih 30 menit di kulkas supaya bumbu meresap (supaya lebih meresap lagi sebaiknya marinasi semalaman di dalam kulkas).\nLangkah 3\nPanaskan minyak goreng kemudian goreng bawang putih hingga kuning & garing, tiriskan. (Usahakan minyak cukup sampai ayam tenggelam saat digoreng)\nLangkah 4\nKemudian goreng ayam hingga coklat keemasan & matang merata (saya pakai api kecil saja) untuk ayamnya goreng bertahap jangan sekali goreng semuanya angkat & tiriskan.\nLangkah 5\nAyam goreng siap di sajikan', ''),
(5, 'Ayam Pop ', 'Ayam Pop adalah hidangan tradisional Indonesia yang berasal dari Betawi, Jakarta. Hidangan ini terkenal karena metodenya yang unik dalam memasak ayam. Ayam Pop dimasak dengan cara dipanggang atau digoreng secara kering tanpa menggunakan bumbu basah atau kuah. Ayam Pop biasanya disajikan dengan kulit yang renyah dan daging ayam yang empuk. Sebelum dimasak, ayam diolah dengan cara diremas menggunakan bumbu kering seperti garam, lada, ketumbar, dan bumbu lainnya. Setelah itu, ayam dipanggang atau digoreng hingga matang dan kulitnya berubah menjadi kecoklatan. Hidangan ini sering dihidangkan dalam potongan kecil yang mudah dinikmati. Ayam Pop biasanya disajikan dengan lalapan, sambal, dan nasi putih. Kelezatan dan keunikannya membuat Ayam Pop menjadi salah satu hidangan yang disukai oleh banyak orang di Indonesia.', 'Bahan-bahan :\n1 ekor ayam kampung (bisa pake ayam pejantan)\n4 bh sereh, geprek\n2 ruas jahe, iris2\n50 ml santan instan\n1 liter air kelapa\n4 sdt garam\n7-8 siung bawang putih, digeprek\nBahan kuah putih :\nSisa air ungkepan ayam\n100 ml santan\n2 sdm tepung terigu larutkan dengan sedikit air\n🍗 Bahan utk sambal ayam pop\n3 lembar daun jeruk\n1/2 sdt terasi\n50 ml santan instan\n1 sdt garam\n1 sdt kaldu bubuk (sy pake kaldu jamur)\n2 sdm saus tomat\n2 sdt gula\nMinyak secukupnya utk menumis\nBumbu halus :\n1 bh tomat merah\n8-10 cabe merah keriting\n8 siung bwg merah\n6 sg bawang putih\nCara Membuat :\nLangkah 1\nPertama tama bersihkan ayam lalu taruh wajan, masukkan 1 liter air kelapa, jahe iris, sereh geprek, bwg putih geprek, 50 ml santan, dan 4 sdt garam...\nLangkah 2\nTutup lalu ungkep ayam dengan api kecil sedang aja selama 1 jam hingga ayam empuk (Sisakan 1/2 air ungkepan)\nLangkah 3\nSambil menunggu ayamnya di ungkep... Buat sambalnya dengan cara menghaluskan menggunakan blender 1 bh tomat, bwg merah, putih, dan cabe keriting dengan dikasih sedikit minyak.... Blend sampai benar2 halus....\nLangkah 4\nPanaskan wajan dengan sedikit minyak lalu tumis bumbu halus bersama dengan daun jeruk... Masak dengan api kecil hingga matang dan mengeluarkan minyak\nLangkah 5\nSetelah mengeluarkan minyak masukkan 50 ml santan instan dan air secukupnya lalu tambahkan garam, gula, kaldu bubuk/kaldu jamur, saus tomat, 1/2 sdt terasi... Aduk rata.. Masak hingga mengental dn matang\nLangkah 6\nSaring sambal utk mendapatkan tekstur yg lembut... Siap disajikan\nLangkah 7\nUtk membuat kuah putih : campur air ungkepan ayam dengan 100 ml santan instan kemudian masukkan cairan tepung terigu nya.. Aduk rata hingga mengental dan meletup letup... Matikan api\nLangkah 8\nGoreng ayam yg sudah di ungkep tadi dengan sedikit minyak sebentar saja \nLangkah 9\nTaruh ayam di piring lalu siram dengan kuah putih dan juga sambalnya... Siap disajikan', ''),
(6, 'Bakso ', 'Bakso adalah hidangan tradisional Indonesia yang populer dan dikenal sebagai bola daging yang biasanya disajikan dalam kuah kaldu. Bakso terbuat dari campuran daging sapi giling, tepung tapioka, dan berbagai bumbu seperti bawang putih, merica, dan garam. Adonan ini kemudian dibentuk bulat dan direbus atau direbus dalam kuah kaldu. Bakso sering dihidangkan dengan mie, bihun, sayuran seperti sawi, dan tambahan seperti tahu, pangsit, atau telur rebus. Kuah kaldu bakso biasanya memiliki cita rasa yang kaya karena proses perebusan daging dan bumbu-bumbu yang digunakan. Warung bakso dapat ditemui di seluruh Indonesia, dan bakso sering dijajakan oleh pedagang kaki lima di jalan-jalan. Variasi dan cara penyajian bakso dapat berbeda-beda di setiap daerah, menciptakan keanekaragaman cita rasa dan bentuk hidangan ini di seluruh nusantara.', 'Bahan-bahan\n250 gr Fillet ayam bagian paha (saya pakai 200 gr ayam dan 50 gr ikan dori)\nhaluskan ayam dgn chopper\n3 siung Bawang putih, cincang halus\n1 buah Wortel, diparut\n20 gr Jamur kuping, rendam air panas hingga mengembang\nKemudian iris tipis halus, saya skip\n15 gr Soun,rendam dan potong2\n1 batang Daun bawang, iris kecil\n1 butir Putih Telur\n1 sdm Tepung sagu\n1 sdm Kecap ikan\n1 sdm Minyak wijen\nsecukupnya Garam, gula, merica, kaldu jamur\nCara Membuat :\nLangkah 1\nBakso : Campur semua bahan bakso diatas\nLangkah 2\nKemudian bentuk bola seperti bakso, rebus diair mendidih hingga mengapung dan tiriskan\nLangkah 3\nBahan kuah :\nAir rebusan jangan dibuang, disaring kemudian didihkan kembali dan tambah air secukupnya\nmasukkan garam,gula merica sesuai selera\nLangkah 4\nMasukkan bakso lo hua biarkan mendidih sebentar kemudian matikan api kompor, tabur daun bawang iris\nSajikan.', ''),
(7, 'Dendeng', 'Dendeng merupakan daging kering yang diiris tipis dalam masakan Indonesia . Daging ini diawetkan melalui campuran gula dan rempah-rempah dan dikeringkan melalui proses penggorengan. Dendeng paling awal dibuat dari daging sapi, dikeringkan agar dapat awet berhari-hari dan dapat dibawa saat bepergian. Dendeng balado atau dendeng batokok , dan merupakan masakan khas Padang, Sumatera Barat , terbuat dari daging sapi yang dipotong tipis-tipis kemudian dikeringkan dan digoreng sebelum ditambahkan cabai dan bahan lainnya.. Ciri khas dendeng batokok adalah irisan daging di-tokok atau dipukul hingga pipih. Setelah daging pipih, goreng dan masak daging dengan sambal cabai merah tumbuk kasar.\r\n', 'Bahan-bahan:\n1 kg daging sapi\n1 ons Cabai merah besar sekitar\n10 buah Cabai rawit setan\n5 siung Bawang putih\n20 siung Bawang merah\nGaram 1 sdt, penyedap 1sdt, kecap bangau secukupnya\n2 lembar Daun salam\n2 batang Serai\nCara Membuat:\nLangkah 1\nPotong-potong terlebih dahulu dagingnya. Aku buat agak lebar dan agak tipis supaya cepat empuk (sesuai selera)\nLangkah 2\nDidihkan air dan rebus daging sekitar 30 menit, atau sampai air benar2 surut dan pastikan daging sudah mulai empuk\nLangkah 3\nKemudian daging yg sudah empuk digoreng sebentar saja, tidak sampai kering\nLangkah 4\nRebus cabai, bawang merah dan bawang putih kemudian ditumbuk atau ulek kasar\nLangkah 5\nGoreng sebentar sambal kasarnya, tambahkan salam dan serai\nLangkah 6\nMasukkan daging yang sudah di goreng ke dalam sambal, tambahkan garam, penyedap, kecap, diaduk supaya merata dan tambahkan air secukupnya. Kemudian masak sekitar 10 menit dan sesekali diaduk\nLangkah 7\nDendeng Batokok sudah matang dan siap disajikan', ''),
(8, 'Gado-gado', 'Gado-gado adalah hidangan tradisional Indonesia yang terkenal sebagai jenis salad sayur dengan bumbu kacang khas. Hidangan ini terdiri dari campuran sayuran segar yang direbus atau direndam air panas, seperti kentang, tauge, kangkung, bayam, dan tahu. Kadang-kadang juga ditambahkan telur rebus atau tempe sebagai pelengkap. Gado-gado disajikan dengan bumbu kacang yang kaya rasa, terbuat dari campuran kacang tanah yang digiling, bawang putih, cabai, gula, tamarind, dan kecap manis. Bumbu ini memberikan cita rasa gurih, manis, asam, dan pedas pada hidangan. Hidangan ini sering disajikan dengan lontong atau nasi, dan dihidangkan dalam porsi besar atau kecil. Gado-gado merupakan hidangan populer yang dapat ditemui di warung-warung makan, restoran, atau penjual kaki lima di seluruh Indonesia. Keunikan dan kelezatan Gado-gado membuatnya menjadi favorit di kalangan masyarakat Indonesia.\r\n', 'Bahan-bahan:\n1 buah timun (iris tipis)\n2 tangkai kacang panjang (potong 1 cm)\n50 gram tauge\n50 gram kol iris\n1 buah terong hijau (di iris tipis)\n1 sendok bawang goreng\nBahan bumbu kacang :\n100 gram kacang tanah goreng\n100 gram gula aren\n1 sendok makan cuka\nSecukupnya garam\n5 buah cabe rawit merah (atau sesuai selera)\n3 sendok makan air matang\n1 buah kentang rebus ukuran sedang (untuk pelembuat tekstur bumbu kacang)\nCara Membuat:\nLangkah 1\nCuci bersih semua bahan sayuran tiriskan hingga tidak ada air yang ter sisa (karena kalo ada sisa air nanti bisa encer ke bumbu),sisihkan dulu\nLangkah 2\nBahan bumbu kacang : Uleg cabe rawit dan garam, masukan kacang sedikit demi sedikit, uleg hingga halus, masukan gula aren uleg lagi hingga tercampur rata, masukan kentang rebus, uleg lagi hingga semuanya tercampur dan benar2 halus, masukan cuka dan air matang,aduk dan uleg lagi sesekali hingga tercampur lagi,koreksi rasa\nLangkah 3\nSetelah semuanya halus dan ter campur masukan sayuran secara bertahap, masukan dulu kacang panjang lalu uleg kasar, dan masukan semua bahan lain nya kecuali timun, terakhir masukan timun..aduk sampai semuanya tercampur\nLangkah 4\nSetelah jadi, taburkan bawang goreng, dan boleh dimakan dengan kerupuk', ''),
(9, 'Grontol', 'Grontol Jagung adalah hidangan tradisional Indonesia yang berasal dari Jawa Tengah dan Jawa Timur. Hidangan ini umumnya terbuat dari jagung muda yang masih dalam cangkangnya, dipadu dengan kelapa parut, gula kelapa, dan garam. Semua bahan tersebut kemudian dibungkus dengan daun pisang dan dikukus hingga matang. Grontol jagung memiliki cita rasa yang unik dan segar karena menggunakan bahan utama jagung muda. Hidangan ini memiliki tekstur yang lembut dari jagung, serat kelapa yang kenyal, dan kelezatan gula kelapa yang memberikan rasa manis alami. Grontol jagung sering dihidangkan sebagai hidangan pencuci mulut atau cemilan tradisional. Hidangan ini dapat ditemukan di berbagai pasar tradisional, warung makan, atau acara perayaan di daerah-daerah yang melestarikan tradisi kuliner Jawa.\r\n', 'Bahan-bahan :\n2 buah jagung ukuran sedang\n1/2 buah Kelapa parut sedang\n1/2 sdt garam\n1 lembar daun pandan\nsecukupnya Gula pasir\nCara Membuat :\nLangkah 1\nRebus jagung hingga matang ±20 menit. Kukus kelapa parut yang sudah dicampur dengan garam dan daun pandan.\nLangkah 2\nAngkat jagung dan kelapa parut. Sisir jagung. Beri taburan kelapa parut dan gula pasir. Sajikan untuk teman ngeteh sore hari.', ''),
(10, 'Gudeg', 'Gudeg adalah hidangan tradisional khas Yogyakarta dan Jawa Tengah, Indonesia. Hidangan ini terbuat dari nangka muda yang dimasak dengan santan kelapa, gula merah, daun salam, serai, dan bumbu-bumbu lainnya. Proses memasaknya melibatkan waktu yang cukup lama hingga nangka muda menjadi lembut dan bumbu meresap. Gudeg umumnya disajikan bersama nasi, ayam kampung, dan telur rebus. Hidangan ini memiliki cita rasa yang unik, kombinasi antara manis dari gula merah, gurih dari santan, dan rempah-rempah yang memberikan karakteristik khasnya. Gudeg biasanya dihidangkan dalam bentuk nasi gudeg, di mana nasi disajikan bersama potongan-potongan gudeg dan lauk pendampingnya. Hidangan ini sering dianggap sebagai salah satu ikon kuliner khas Yogyakarta dan Jawa Tengah. Gudeg dapat ditemui di warung-warung tradisional, restoran, atau menjadi hidangan khas dalam berbagai acara adat, perayaan, atau hari-hari spesial di Indonesia.\r\n', 'Bahan-bahan :\n500 gr nangka muda, potong2 dan cuci bersih\n5 telur rebus\n150 gr gula merah yg warnanya gelap, disisir\n2 kantong teh celup\n1 saset santan instan uk 65 ml larutkan dengan 1 liter air\n1/2 sdm garam\n1 sdm kaldu bubuk\nBumbu cemplung :\n3 lbr daun salam\n2 lbr daun jeruk\n1 btg sereh, geprek\n2 ruas lengkuas, geprek\nBumbu halus :\n5 bawang merah\n3 bawang putih\n3 kemiri\n1/2 sdm ketumbar bubuk\nCara Membuat:\nLangkah 1\nSiapkan bahan dan bumbu\nLangkah 2\nTata dalam panci : daun salam, daun jeruk, lengkuas, sereh, gula merah dan bumbu halus.\nMasukan nangka muda, telur dan teh celup.\nBeri santan dan masak dengan api sedang selama 15 menit dihitung dari mulai mendidihnya santan. Keluarkan kantong tehnya.\nLalu masak lagi selama 1 jam.\nLangkah 3\nIni penampakan gudeg setelah dimasak selama 1 jam.\nPindahkan ke magic com dan tekan tombol cook, masak selama 15- 30 menit (sy 30 menit).\nLanjutkan dalam posisi warm selama 6- 7 jam.\nLangkah 4\nGudeg setelah proses warm selama 5 jam sudah bisa disantap.\nPindahkan ke piring saji dan siap dinikmati', ''),
(11, '', '', '', ''),
(12, 'Gulai tambunsu', 'Gulai tambunsu atau tambusu adalah makanan khas Sumatera Barat. Tambusu terbuat daripada usus lembu atau usus kerbau, dengan kuah gulai yang pekat dan diisi dengan telur putar berempah. Tidak hanya telur, tetapi tambusu boleh diisi dengan bahan lain seperti tauhu, tempe atau potongan kentang. Proses untuk memasak dan membuat gulai tambusu mengambil masa yang lama. Di samping itu, makanan ini juga tersebar diseluruh daerah di Indonesia khususnya Jawa. Lauk ini juga sesuai makan bersama nasi Kapau.\r\n', 'Bahan-bahan :\n1/2 kg usus sapi\nIsian usus :\n5 buah tahu putih uk sedang\n5 butir telor ayam\n4 siung bawang putih dihaluskan\n1 bungkus kaldu bubuk rasa sapi\n1 sdt kunyit bubuk\nBumbu kuah :\n1 bungkus bumbu instan rasa rendang\n2 lb daun salam\n3 lb daun jeruk purut\n1 sereh digeprek\n1 ruas laos\n1 sachet kaldu bubuk rasa sapi\n2 bungkus santan instan @65 ml\nSegenggam kelapa sangrai yg sdh dihaluskan (optional)\nsecukupnya Gula dan garam\nCara Membuat:\nLangkah 1\nSiapkan semua bahan dan bumbu\nLangkah 2\nTahu dihaluskan, cukup pake spatula/ sendok. Lalu campur dengan bumbu2 untuk isi, aduk2 hingga merata. Terakhir masukkan telor, aduk rata. Sisihkan\nLangkah 3\nUsus dicuci bersi dg air mengalir sambil digosok2 hingga bersih, cuci sebentar dg jeruk nipis, bilas. Sisihkan.\nIsian tahu, masukkan ke piping bag, semprotkan ke dalan usus. Sebelumnya ujung usus diikat dg tali rafia kemudian beri isian dan jangan terlalu penuh (sy 3/4 bg) biar tidak meledak saat dimasak.\nLalu ikat lagi di ujung yg satunya. Rebus Hingga matang (sekitar 20 menit), angkat, tiriskan.\nLangkah 4\nDi wajan tumis bumbu hingga harum, tuangi air dan bumbu lainnya. Setelah bbrp saat, masukkan santan. Aduk terus dan usus yg sdh diisi td dimasukkan ke kuah. Masak hingga kuah mengental, tes rasa. Klu rasa sdh pas. Matikan api, tata tambunsu di wadah saji lalu sajikan.', ''),
(13, 'Gulai Tunjang', 'Gulai Tunjang adalah hidangan tradisional Indonesia yang berasal dari Padang, Sumatra Barat. Hidangan ini terkenal karena menggunakan tunjang sapi sebagai bahan utama. Tunjang adalah bagian kaki sapi yang terutama terdiri dari tulang rawan dan daging di sekitarnya. Gulai Tunjang disajikan dalam kuah kental dan kaya rempah yang terbuat dari campuran santan, bumbu rempah khas Minangkabau seperti serai, daun jeruk, lengkuas, kunyit, jahe, dan cabai. Rasa gulai ini umumnya gurih, pedas, dan kaya rempah, memberikan cita rasa yang khas dari masakan Padang. Hidangan ini biasanya dihidangkan dengan nasi putih dan dapat disertai dengan kerupuk atau lontong. Gulai Tunjang sering dijumpai di rumah makan Padang atau warung-warung makan khas Minangkabau di seluruh Indonesia.\r\n', 'Bahan-bahan:\n1/2 kg daging sapi bagian sengkel\n1/2 kg kikil sapi\nBumbu Sangrai :\n1 sdm ketumbar\n4 bh kembang lawang\n4 bh kapulaga\n4 bh cengkeh\n3 cm kayu manis\n1 bh pala (sy ganti dgn 1 sdt bubuk pala)\nBumbu Halus :\n12 bh bawang merah\n10 bh bawang putih\n2 ruas kunyit\n1 ruas jahe\n1 ruas lengkuas\n10 bh cabe rawit (utk yg suka pedes)\n15 bh cabe merah keriting\nBumbu cemplung:\n1 lembar daun kunyit\n4 lembar daun jeruk\n5 lembar daun salam\n1 ruas lengkuas geprek\n2 bh sereh di geprek\n3 bh adas\nsecukupnya Garam\nsecukupnya Penyedap rasa\n500 ml santan cair\nMinyak goreng untuk menumis\nCara Membuat:\nLangkah 1\nRebus daging dan kikil dgn daun salam serta irisan kunyit di air mendidih. Ulang sampai empuk dan tidak berbau sapi lalu tiriskan\nLangkah 2\nMasukan bumbu sangrai ke dalam wajan lalu sangrai hingga berwarna kecoklatan kemudian dinginkan. Setelah itu blender hingga menjadi bubuk\nLangkah 3\nSiap bumbu yang akan dihaluskan lalu blender hingga halus.\nLangkah 4\nSiapkan wajan lalu panaskan dengan minyak goreng kemudian tumis.\nLangkah 5\nMasukan bumbu cemplungnya lalu tumis hingga airnya asat dan harum. Kemudian masukan larutan santan dan dapat ditambahkan air sesuai selera lalu aduk rata dan didihkan\nLangkah 6\nMasukan potongan daging dan kikil yg telah direbus kemudian aduk rata dan masak selama kurleb 30-45 menit\nLangkah 7\nTambahkan garam dan penyedap rasa lalu aduk rata, apabila sudah agak mengental kemudian koreksi dan cek rasa. Apabila sudah pas matikan api.\nLangkah 8\nGulai cincang tunjangan padang siap disajikan dengan nasi hangat', ''),
(14, 'Kue ape', 'Kue ape, juga dikenal sebagai serabi Jakarta, dianggap sebagai pancake India khas Indonesia yang dikenal sebagai appam. Pancake khas Indonesia ini biasanya terbuat dari tepung terigu, tepung beras, dan santan serta beberapa bahan lain seperti gula pasir dan baking powder. Kue ini bisa dikenali dari warna hijau cerah daun suji dan bentuknya yang seperti piring. Bagian tengah kue ape berwarna hijau cerah dan teksturnya lembut, sedangkan bagian luarnya berwarna coklat dan renyah. Seringkali dibumbui dengan pandan, yang memberi warna hijau khas pada kue ini. Hidangan ini biasanya disiapkan dan dijual oleh pedagang kaki lima yang berlokasi di pusat jajanan dan pasar kaki lima.\r\n', 'Bahan-bahan:\n150 gr tepung beras\n100 gr tepung terigu\n100 gr gula pasir\n1/2 sdt garam\n1 sdm baking powder\n1 sdt pasta pandan\n150 ml air matang\n100 ml santan instant\nCara Membuat:\nLangkah 1\nAyak tepung2\nLangkah 2\nCampur semua bahan kering lalu tambahakan sedikit sedikit air + santan aduk rata sampai tidak ada yg menggumpal\nLangkah 3\nDiamkan 45 menit - 1 jam. Aduk kembali Panaskan teflon mini dengan api kecil, kuas teflon dengan margarin / sedikit minyak kelapa Tuang adonan 1 centong sedang dari sisi atas (kulit garing) lalu tutup dan diamkan selama 3-4 menit. Buka dan cek kulit bawah. Kalau sudah kecoklatan dan bagian gendut sudah matang, angkat dan kue ape siap di nikmati.', ''),
(15, 'Bika Ambon ', 'Bika Ambon adalah kue tradisional Indonesia yang berasal dari daerah Ambon, Maluku. Kue ini memiliki tekstur yang unik, yaitu kenyal dan berlubang-lubang seperti spons. Bika Ambon terbuat dari campuran tepung sagu, tepung beras, santan, gula, telur, dan rempah-rempah seperti daun pandan yang memberikan aroma khas. Proses pembuatannya melibatkan fermentasi adonan, yang memberikan tekstur berlubang pada kue saat dipanggang. Rasa kue ini umumnya manis dengan sedikit rasa gurih dari santan kelapa. Bika Ambon sering dihiasi dengan daun pandan di bagian atasnya. Kue ini sering dijadikan oleh-oleh khas daerah Ambon dan juga ditemukan di berbagai daerah di Indonesia. Karena keunikan rasanya dan teksturnya yang khas, Bika Ambon sering menjadi favorit di berbagai acara, perayaan, atau dijadikan sebagai oleh-oleh yang disukai.\r\n', 'Bahan Santan:\n100 ml santan\n2 lbr daun pandan\n5 lbr daun jeruk\n1 batang serai\n1 ruas kunyit, potong-potong\nBahan Kue:\n3 butir telur\n400 ml santan, masak\n300 gr tepung sagu\n250 gr gula pasir\nBahan Biang:\n1 sdm terigu\n6 sdm air hangat\n1 bungkus fermipan\n1 sdt gula pasir\nCara Membuat:\nLangkah 1\nMasak semua bahan santan di atas api sedang. Masak hingga santan menjadi 400 ml, angkat dan dinginkan.\nLangkah 2\nCampurkan jadi satu bahan biang. Kemudian diamkan selama 20-15 menit.\nLangkah 3\nMixer gula dan telur gingga gula larut.\nLangkah 4\nTurunkan kecepatan mixer, masukkan bahan santan dan tepung sagu secara bergantian. Aduk rata.\nLangkah 5\nTambahkan biang, aduk kembali dan matikan mixer.\nLangkah 6\nSaring adonan untuk menyaring tepung yang masih bergerindil.\nLangkah 7\nKemudian tutup adonan dan diamkan selama 3 jam.\nLangkah 8\nSiapkan loyang yang telah diolesi carlo. Panaskan terlebih dahulu loyang di dalam oven.\nLangkah 9\nTuangkan adonan ke dalam loyang panas. Panggang di dalam suhu 180 derajat celcius selama 40 menit. Biarkan oven sedikit terbuka selama 30 menit pertama, kemudian tutup oven hingga rapat, panggang hingga matang.\nLangkah 10\nJika sudah matang, angkat dan biarkan dingin.', ''),
(16, 'Kue Cenil', 'Kue Cenil adalah kue tradisional Indonesia yang memiliki bentuk bulat kecil dan terbuat dari campuran tepung sagu atau tepung beras yang dicampur dengan air dan pewarna alami seperti daun pandan. Adonan kue ini kemudian dibentuk menjadi bulatan kecil dan direbus dalam air mendidih hingga mengapung. Setelah matang, kue cenil biasanya dicampur dengan kelapa parut yang telah diparut halus. Kue ini memiliki tekstur kenyal dan rasa manis, serta cita rasa khas yang berasal dari kelapa parut. Kue Cenil sering dihidangkan sebagai kudapan ringan atau cemilan tradisional. Karena bentuknya yang kecil dan cita rasanya yang lezat, kue ini sering menjadi pilihan dalam berbagai acara, seperti arisan, perayaan, atau sebagai sajian khas di pasar tradisional di Indonesia.\r\n', 'Bahan-bahan:\n150 gram kelapa parut (setengah tua)\nSejumput Garam\nSecukupnya gula pasir\n100 gram/10 sdm tepung terigu\n100 gram/10 sdm tepung tapioka\n130 ml air hangat\nSejumput garam\nSecukupnya pewarna makanan (aku pakai pasta pandan & merah rose)\nNB: untuk air hangatnya bisa ditambahin/dikurangin ya\nCara Membuat:\nLangkah 1\nSiapkan semua bahan terlebih dahulu.\nLangkah 2\nKukus parutan kelapa yg sudah dicampur dengan garam kira² 10 menit. Setelah itu sisihkan.\nLangkah 3\nMasukan tepung terigu, tepung tapioka, dan garam. Aduk sampai rata.\nLangkah 4\nSetelah itu beri air sedikit demi sedikit, aduk sampai adonan tercampur rata.\nLangkah 5\nBagi adonan menjadi 3, taruh dalam wadah. Masing² diberi pewarna, satu warna pasta pandan, dua merah rose dan yg ketiga ngga perlu diberi warna.\nLangkah 6\nAmbil adonan sedikit, bentuk menjadi stik atau sesuai selera. Sisihkan. Lakukan sampai adonan habis.\nLangkah 7\nRebus air hangat dengan panci. Setelah mendidih, masukan adonan yg berwarna putih terlebih dahulu. Tunggu sampai adonan mengapung (tanda sudah matang), angkat dan tiriskan.\nLangkah 8\nLakukan hal yg sama sampai adonan pandan dan rose nya habis.\nLangkah 9\nSetelah semua adonan sudah direbus, masukan dalam parutan kelapa. Aduk² sampai adonan tidak ada yg menempel satu dengan yg lain.\nLangkah 10\nTaburin dengan gula pasir secukupnya. Kue cenil siap disajikan ditemani dengan teh anget. ', ''),
(17, 'Kue Dadar Gulung', 'Kue Dadar Gulung adalah kue tradisional Indonesia yang memiliki ciri khas adonan dadar tipis yang diisi dengan campuran kelapa parut yang telah dicampur dengan gula kelapa. Adonan dadar umumnya terbuat dari campuran tepung beras, santan, dan daun pandan yang memberikan warna hijau khas pada dadar. Proses pembuatannya melibatkan penyebaran adonan dadar tipis di atas penggorengan datar atau wajan dan kemudian diisi dengan campuran kelapa parut yang manis. Setelah itu, dadar digulung sehingga membentuk silinder atau gulungan. Kue Dadar Gulung memiliki rasa manis, lembut, dan gurih dari campuran kelapa parut. Kue Dadar Gulung sering dijumpai di pasar tradisional, toko kue, atau kios makanan di Indonesia. Kue ini sering dihidangkan sebagai kudapan ringan atau cemilan yang populer dalam berbagai acara, perayaan, atau sebagai sajian sehari-hari di rumah.\r\n', 'Bahan-bahan:\n150 gr terigu\n30 gr tepung beras\n300 cc air\n1 butir telur\n1 sachet kental manis\n1 sdt margarin cair\n1 sdt pasta pandan\n2 tetes pewarna hijau tua\n1/2 butir kelapa, kupas, parut memanjang\n100 ml air\n1 sdm gula merah yang disisir\nsecukupnya Gula pasir\n1/2 sdt garam\nCara Membuat:\nLangkah 1\nCampur terigu, tepung beras, garam, tuang air sedikit sedikit sambil diaduk, agar tidak bergerindil, masukkan telur, kental manis aduk sampai halus. Tambahkan margarin, aduk rata.\nLangkah 2\nTambahkan pasta dan pewarna, aduk rata\nLangkah 3\nUntuk unti, campur kelapa parut, air, gula merah, garam masak dengan api kecil, tambahkan gula pasir, tes rasa manis yang diinginkan, masak sampai air habis,sambil diaduk-aduk agar tidak gosong.\nLangkah 4\nBuat dadar, lakukan sampai habis\nLangkah 5\nBila suka dadar yg bertekstur, sebelum dituang adonan, wajan teflonnya dioles minyak goreng dengan kuas, setelah panas baru dituangi adonan\nLangkah 6\nIsi dadar dengan unti, gulung, biar cantik bungkus dengan plastik', ''),
(18, 'Getuk Lindri', 'Getuk Lindri adalah salah satu makanan tradisional Indonesia yang terbuat dari ketan putih yang dimasak, kemudian diuleg atau dihaluskan dan dicampur dengan kelapa parut serta gula kelapa. Adonan ini kemudian dibentuk menjadi silinder panjang dan dipotong-potong menjadi bagian kecil yang sering kali berbentuk persegi atau segi empat. Getuk Lindri sering dihiasi dengan kelapa parut di sekitarnya atau ditaburi dengan kelapa parut di atasnya. Rasanya manis, kenyal, dan memiliki aroma khas kelapa. Makanan ini sering dihidangkan sebagai kudapan tradisional di berbagai acara seperti perayaan atau upacara adat. Getuk Lindri dapat ditemui di pasar tradisional, warung makan, atau toko kue di Indonesia. Keunikan bentuk dan cita rasa dari Getuk Lindri membuatnya menjadi pilihan yang disukai dalam berbagai kegiatan dan perayaan masyarakat Indonesia.\r\n', 'Bahan-bahan:\n400 grm kelapa parut\n225 grm gula pasir\n1/2 sdt garam\n1/2 sdt vanili paste\n100 ml air\n850 grm singkong (berat udah dikupas dan dibersihkan)\n150 grm gula pasir\n2 sdm penuh margarin\n1/2 sdt vanilli\nBbrp tetes pewarna merah cabe \n1/4 buah kelapa setengah tua, parut. Campur dengan sedikit garam. Lalu kukus 15 mnt\nCara Membuat:\nLangkah 1\nBikin unti kelapa terlebih dahulu. Di pan tuang air lalu gula pasir dan garam. Aduk hingga gula dan garam larut. Masukkan kelapa parut dan tambahkan daun pandan yang disimpulkan. Masak hingga kering. Sisihkan.\nLangkah 2\nKukus singkong yang sudah dikupas dan dicuci bersih hingga empuk. Tiriskan. Lalu selagi panas tumbuk dengan ulekan hingga lembut dan punel. Singkirkan seratnya saat ditumbuk.\nLangkah 3\nTambahkan gula pasir, margarin, garam, dan vanili, aduk hingga rata. Bagi adonan menjadi dua bagian. Beri perasa/ pewarna makanan sesuai selera.\nLangkah 4\nPulung2 adonan. Untuk adonan kulit 20 gram. Untuk adonan unti 15 gram. Gepengkan adonan. Beri isian. Tutup lalu pulung-pulung.\nLangkah 5\nCetak dengan cetakan mooncake. Lakukan hingga adonan habis\nLangkah 6\nSajikan dengan kelapa kukus yang diparut.', ''),
(19, 'Kue Kastangel', 'Kue Kastangel adalah salah satu kue tradisional Indonesia yang terbuat dari campuran mentega, gula, dan tepung terigu, yang dicetak dan dipanggang hingga kecoklatan. Kue ini memiliki bentuk seperti batang kastange, sehingga diberi nama \"kastangel.\" Proses pembuatannya melibatkan pencetakan adonan yang umumnya diberi warna kuning dengan cetakan khusus atau dengan menggunakan alat sederhana. Setelah dicetak, kue kastangel kemudian dipanggang hingga matang. Kue ini memiliki tekstur renyah dan rasa butter yang lezat. Kue Kastangel sering dihidangkan sebagai kudapan di berbagai acara, seperti perayaan atau momen-momen spesial. Kue ini juga sering dijadikan oleh-oleh karena kelezatan dan kemudahannya dalam penyimpanan. Meskipun sederhana, Kue Kastangel memiliki tempat khusus di hati pecinta kue tradisional Indonesia.\r\n', 'Bahan-bahan:\n75 gram Keju edam\n75 gram Keju permesan\n50 gram Wisyman\n100 gram Anchor\n200 gram Blueband\nTerigu kunci biru kira2 saja sampai adonan bs dipulung (siapkan lk 500 gram)\n50 gram Maizena\n50 gram Susu bubuk\nKuning telor utk olesan\nKeju cheddar utk taburan\nCara Membuat:\nLangkah 1\nCampur 3 jenis mentega,aduk pk spatula,mskkn keju yg sdh di parut,susububuk,maizena dan terigu sdkt2\nLangkah 2\nAduk dan rasakan sampai kira2 bs dipulung\nLangkah 3\nCetak,oles kuning telur dan keju parut(cheddar)\nLangkah 4\nPanggang di oven sampai matang(golden brown)\nLangkah 5\nReswp tanpa kuning telur,hasilnya lbh renyah dan garing', ''),
(20, 'Klepon', 'Klepon adalah salah satu kue tradisional Indonesia yang terkenal dan memiliki ciri khas bola kecil yang diisi dengan kelapa parut dan gula kelapa. Kue ini terbuat dari adonan ketan yang dibentuk bulat, kemudian diisi dengan campuran kelapa parut yang telah dicampur dengan gula kelapa yang manis. Setelah diisi, klepon kemudian direbus sebentar hingga ketan matang, dan akhirnya, bola kecil ini dilapisi dengan kelapa parut. Klepon memiliki warna hijau karena menggunakan pewarna alami dari daun suji atau pandan. Rasa kue ini unik dengan kombinasi kenyalnya ketan, manisnya kelapa parut, dan gula kelapa yang legit. Klepon sering dijumpai di pasar tradisional, toko kue, atau warung kopi di Indonesia. Kue ini sering dihidangkan dalam acara-acara khusus, seperti perayaan atau acara keluarga, dan menjadi salah satu kudapan tradisional yang disukai oleh banyak orang.\r\n', 'Bahan-bahan:\n1/4 Kelapa parut\nGaram\n250 gram Tepung ketan\n50 gram Tepung beras\nsecukupnya Air matang\n3 lembar Daun Pandan\nGula Jawa 1 butir (di iris tipis-tipis)\nCara Membuat:\nLangkah 1\nParut kelapa dan taburi garam lalu kukus kurang lebih 30 menit\nLangkah 2\nMasukan tepung ketan dan tepung beras perbandingan 5 : 2\nLangkah 3\nBlender air pandan dengan air panas\nLangkah 4\nCampurkan air pandan dan adonan tepung, lalu uleni sampai kalis tambah pewarna makanan rasa pandan untuk mencerahkan warna agar tidak pucat\nLangkah 5\nRebus air dengan menambah 1 makan sendok minyak sayur, jika sudah mendidih masukan adonan klepon untuk di rebus. Tunggu hingga mengambang, adonan siap di angkat dan disajikan. Tunggu klepon hingga dingin, setelahnya taburkan kelapa parut untuk di sajikan\nLangkah 6\nKlepon gula merah siap disajikan. ', ''),
(21, 'Kue Lapis', 'Kue Lapis adalah salah satu kue tradisional Indonesia yang terkenal karena memiliki lapisan-lapisan yang cantik dan warna-warni. Kue ini terbuat dari adonan yang terdiri dari tepung beras, santan, gula, dan pewarna makanan alami. Adonan ini kemudian dipanggang atau dikukus secara bertahap untuk menciptakan lapisan yang berbeda warna dan tekstur. Proses pembuatan kue lapis membutuhkan kesabaran karena setiap lapisan harus dipanggang atau dikukus secara terpisah sebelum ditumpuk. Kue Lapis umumnya memiliki tampilan yang memikat dengan lapisan-lapisan yang terlihat seperti permainan warna. Kue Lapis sering dihidangkan pada acara perayaan, ulang tahun, atau sebagai kudapan tradisional di Indonesia. Selain rasa manis yang lezat, keindahan visual kue ini juga membuatnya menjadi favorit di kalangan masyarakat Indonesia.\r\n', 'Bahan Kue Lapis Singkong :\n1 bungkus agar agar plain\n170 gr gula pasir\n1/2 sdt vanili bubuk\n300 ml santan\n800 gr singkong (parut dan peras airnya)\nPewarna makanan\nBahan Taburan :\n80 gr kelapa parut (setengah tua)\nSejumput garam\n1 lembar daun pandan (simpulkan)\nCara Membuat:\nLangkah 1\nSiapkan semua bahan bahan,\nOles loyang dgn sedikit minyak goreng. Siapkan baskom/mangkok, masukan agar agar plain, gula pasir, vanili bubuk dan santan, aduk sampai semua larut.\nLangkah 2\nTambahkan singkong parut,\nAduk kembali sampai tercampur rata, bagi menjadi 3 adonan, beri warna merah muda, warna hijau muda, dan tanpa pewarna. Tuang adonan tanpa pewarna ke dalam loyang, kukus ke dalam panci (yang sudah mendidih airnya) selama 15 menit.\nLangkah 3\nSetelah adonan pertama set, timpa dgn adonan warna hijau, ratakan dan kukus kembali selama 15 menit. Setelah adonan hijau set, timpa dgn adonan warna merah muda (adonan terakhir) ratakan, dan kukus kembali selama 25 menit. Tunggu dingin lalu keluarkan dari loyang.\nLangkah 4\nPotong potong ukuran sesuai selera. Siapkan bahan taburan, campur rata kelapa dgn garam, tambahkan daun pandan lalu kukus selama 10 menit atau sampai kelapa matang dan wangi.\nLangkah 5\nLumuri kue lapis singkong dgn kelapa parut, nikmati dengan teh disore hari.', ''),
(22, 'Lemper', '\"\r\nLemper adalah salah satu kue tradisional Indonesia yang terkenal. Kue ini terbuat dari ketan yang diisi dengan daging ayam yang dimasak dengan bumbu khas, seperti kelapa parut, serai, daun jeruk, dan santan kelapa. Adonan ketan yang diberi isian daging ayam ini kemudian dibungkus dengan daun pisang dan dibentuk seperti silinder atau batang. Kue lemper memiliki cita rasa yang khas dan lezat, dengan kombinasi antara kelembutan ketan, aroma harum daun pisang, dan kelezatan isian daging ayam yang berbumbu. Kue ini sering disajikan dalam acara khusus, perayaan, atau sebagai camilan sehari-hari. Lemper merupakan salah satu kue tradisional yang banyak dijumpai di pasar-pasar tradisional, toko kue, dan warung makan di seluruh Indonesia. Keunikan rasa dan presentasi kue lemper membuatnya menjadi pilihan populer di kalangan masyarakat Indonesia.\"\r\n', 'Bahan-bahan:\n1 liter beras ketan\n1 butir santan\nsecukupnya garam\nsecukupnya gula\n1 buah jeruk nipis\n9 siung bawang merah\n7 siung bawang putih\nsecukupnya lada\nsecukupnya pala\nsecukupnya garam\nsecukupnya gula\nsecukupnya penyedap rasa ayam\nCara Membuat:\nLangkah 1\nSiapkan bahan bahan\nLangkah 2\nMasukan beras ketan untuk di kukus\nLangkah 3\nMasak santan yang diberi gula dan garam, aduk sampai mendidih\nLangkah 4\nSetelah beras dikukus 30 menit angkat lalu tambahkan santan yang sudah dimasak tadi.\nLangkah 5\nBeras ketan yang sudah dikukus kurang lebih 30 menit ditambah santan yang sudah di masak tambah jeruk nipis\nLangkah 6\nKemudian dikukus kurang lebih 30 menit\nLangkah 7\nSetelah di kukus kurang lebih 30 menit, angkat beras ketan yg sudah di masak kemudian bungkus ketan yg sudah di beri suwiran ayam\nLangkah 8\nLemper siap dimakan', ''),
(23, 'Kue Lumpur', '\"\r\nKue Lumpur adalah salah satu kue tradisional Indonesia yang memiliki ciri khas lumpur lembut dan rasa manis yang lezat. Kue ini terbuat dari adonan yang umumnya mengandung tepung beras, kelapa parut, santan, gula, dan telur. Adonan ini kemudian dipanggang dalam cetakan khusus atau bisa juga menggunakan daun pisang sebagai wadahnya. Setelah dipanggang, kue lumpur biasanya memiliki tekstur yang lembut, agak kenyal, dan seringkali memiliki lapisan kelapa parut di atasnya. Rasa manis yang berasal dari gula membuatnya cocok sebagai camilan atau kudapan ringan. Kue Lumpur sering dijumpai di pasar tradisional, toko kue, atau warung-warung makan di Indonesia. Kelezatan dan sifatnya yang praktis membuat kue ini populer di kalangan masyarakat Indonesia sebagai salah satu variasi kue tradisional yang mudah dinikmati dalam berbagai kesempatan.\"\r\n', 'Bahan-bahan:\n250 gram ubi kuning,kupas rebus,berat setelah dikukus\n170 gram gula pasir\n220 gram terigu protein sedang\n2 butir telur\n1 kuning telur\n450 ml air+ 6 sdm penuh fiber creame, bisa diganti santan\n100 gram palmia royal dilelehkan\nSejumput garam\nTopping\nSecukupnya kismis,\nJika tidak suka kismis bisa diganti sukade,keju atau coklat chip\nCara Membuat:\nLangkah 1\nKupas ubi kupas cuci bersih potong -potong rebus dengan daun pandan sampai empuk,angkat tiriskan,timbang 250 gram\nLangkah 2\nBikin larutan fiber creame sisihkan. Ambil 250 ml larutan masukkan ke blender tambah kan gula pasir dan dan ubi blender hingga halus\nLangkah 3\nSetelah halus tuang kedalam baskom / wadah yang lebar kemudian masukkan telur aduk dengan whisk masukkan terigu dan sisa larutan fiber creame tadi aduk rata masukkan margarin leleh, terakhir masukkan vanilli jika masih bergerindil tepung nya saring\nLangkah 4\nPanaskan Snack maker,setelah panas masukkan adonan tutup pan setelah adonan naik tambah topping saya pake kismis coklat yang kecil-kecil\nLangkah 5\nSetelah matang angkat dengan tusuk sate dan spatula', ''),
(24, 'Nagasari', 'Nagasari adalah salah satu kue tradisional Indonesia yang populer dan memiliki ciri khas tertentu. Kue ini terbuat dari adonan tepung beras yang dicampur dengan kelapa parut dan santan kelapa, kemudian dibungkus dalam daun pisang dan dikukus hingga matang. Isian nagasari umumnya terdiri dari potongan pisang yang telah dikupas. Nagasari memiliki tekstur yang lembut dan kenyal, serta cita rasa yang manis dan gurih dari kombinasi kelapa parut, santan, dan pisang. Kue ini sering dihidangkan sebagai kudapan atau jajanan tradisional di Indonesia. Selain itu, nagasari juga sering ditemui dalam berbagai acara perayaan, seperti Lebaran atau acara keluarga. Keistimewaan nagasari tidak hanya terletak pada rasanya yang lezat, tetapi juga pada aroma harum daun pisang yang digunakan untuk membungkusnya. Kue tradisional ini merupakan salah satu favorit di berbagai daerah di Indonesia.\r\n', 'Bahan-bahan:\n1 buah pisang raja ukuran besar, potong serong jadi 7 bagian\n400 ml santan kekentalan sedang\n1/4 sdt garam\n1 sdm gula pasir (resep asli pake 65 gram)\n1 lembar daun salam (resep asli pake daun pandan)\n100 gram tepung beras\n50 gram tepung tapioka\nSecukupnya daun pisang\nCara Membuat:\nLangkah 1\nSiapkan bahan-bahan.\nLangkah 2\nRebus santan, gula pasir, garam, dan daun salam hingga mendidih menggunakan wajan supaya mudah mengaduknya. Dinginkan.\nLangkah 3\nSetelah dingin, masukkan tepung beras dan tepung tapioka, aduk pakai whisk hingga tidak ada tepung yang bergerindil.\nLangkah 4\nNyalakan api, masak sambil terus diaduk hingga mengental. Pastikan tidak ada tepung yang menggumpal, ya\nLangkah 5\nAmbil selembar daun pisang, letakkan kurang lebih 3 sdm adonan, pipihkan lalu beri sepotong pisang kemudian tutup pisang dengan adonan.\nGulung daun pisang lalu lipat atas bawah sehingga kedua ujungnya bertemu. Lakukan hingga selesai. Punya saya jadi 7 buah. Banyak sedikitnya adonan sesuaikan dengan kebutuhan teman-teman, ya.\nLangkah 6\nKukus nagasari selama 20 menit. Ini tahan sekitar 15 jam suhu ruang. Jika ingin bertahan lebih lama lagi, silakan kukus lebih lama.', ''),
(25, 'Pastel', 'Pastel adalah salah satu jenis kue tradisional Indonesia yang terkenal. Kue ini biasanya memiliki bentuk bulat atau setengah bulat dan terbuat dari adonan kulit tepung yang tipis, yang kemudian diisi dengan campuran daging ayam cincang, kentang, telur, dan sayuran seperti wortel. Isian tersebut biasanya dibumbui dengan bumbu rempah yang khas Indonesia seperti bawang putih, bawang merah, ketumbar, dan lada. Setelah diisi, kulit pastel biasanya disegel dan kemudian digoreng hingga kulitnya menjadi renyah dan berwarna keemasan. Pastel memiliki cita rasa yang gurih dan lezat, dengan kombinasi tekstur renyah dari kulit dan isian yang lembut. Kue pastel sering dijual di warung-warung kue, toko roti, atau kios-kios makanan di Indonesia. Selain sebagai camilan sehari-hari, pastel juga sering disajikan dalam acara-acara spesial, pesta, atau sebagai hidangan ringan di waktu santai.\r\n', 'Bahan-bahan:\n75 gr tepung terigu segitiga\n50 gr tepung terigu kunci\n1 sdm margarin\n7 sdm air dingin\nsejumput garam\nBahan isian:\n1 buah bawang merah\n1 bh bawang putih\n1/2 keping bihun jagung\n1 bh wortel uk kecil\n2 lbr kol\n1 batang daun bawang\n1 batang seledri\n1/2 sdt ladaku\n1/2 sdt kaldu bubuk\n1/2 sdt garam\nminyak goreng untuk menggoreng\nCara Membuat:\nLangkah 1\nSiapkan bahan kering, campur semua dan aduk aduk, uleni hingga kalis, diamkan 15 menit, lalu timbang adonan per 20 gr\nLangkah 2\nRendam bihun dalam air mendidih\nLangkah 3\nItis tipis bawang merah, bawang putih, lalu tumis dengan sedikit minyak sampai harum, masukkan wortel dan kol, tunggu layu, masukkan lada bubuk, garam, kaldu bubuk, dan gula pasir, cek rasa,masukkan bihun hingga air habis, masukkan daun bawang dan seledri, dinginkan\nLangkah 4\nGilas adonan kulit dengan pin lalu isi dengan bihun, tutup pastel, kerjakan sampai adonan habis\nLangkah 5\nPanaskan minyak sampai bener bener panas dengan api sedang, goreng pastel hingga golden brown, angkat tiriskan\nLangkah 6\nSajikan bersama cabe ijo, sangatlah enak', ''),
(26, 'Putri Salju', 'Putri Salju adalah salah satu jenis kue tradisional Indonesia yang memiliki ciri khas tampilan putih bersalut gula bubuk, menyerupai lapisan salju yang lembut. Kue ini biasanya terbuat dari adonan yang terdiri dari tepung terigu, mentega, susu, dan telur. Adonan kemudian dibentuk bulat-bulat kecil dan dipanggang hingga matang. Setelah matang, kue Putri Salju sering dicelupkan atau ditaburi dengan gula halus atau gula bubuk, memberikan kesan putih bersalju yang khas. Kue ini memiliki tekstur yang lembut dan rapuh dengan rasa butter yang kaya. Putri Salju sering dihidangkan sebagai kudapan di berbagai acara, termasuk perayaan, acara keluarga, atau sebagai hadiah pada waktu-waktu tertentu. Kue Putri Salju merupakan salah satu kudapan yang populer dan dihargai di Indonesia karena cita rasanya yang lezat dan penampilannya yang cantik.\r\n', 'Bahan-bahan:\n70 gr gula halus\n100 gr mede bubuk\n30 gr keju parut\n225-250 gr tepung terigu protein rendah (kunci biru)\n180 gram butter mix margarin\nbahan tabur:\n100 gr gula halus\n200 gr gula dingin\n50 gr susu bubuk\nCara Membuat:\nLangkah 1\nMixer butter mix dan gula halus sebentar cukup 2 menit dengan kecepatan rendah. Jika menggunakan whisker 2-3 menit. Lalu tambahkan mede bubuk. Aduk dengan whisk sampai merata.\nLangkah 2\nTambahkan keju parut. Aduk kembali sampai merata.\nLangkah 3\nSisihkan whisk. Tuang 225 gram tepung. Aduk dengan spatula sampai tercampur rata. Bisa juga diuleni atau gunakan dengan tangan sebentar. Siapkan plastik wrap atau plastik kiloan. Ambil sedikit adonan. Pipihkan dengan cara digilas rolling pin. Ketebalan 1/2 cm. Cetak bentuk bulat.\nLangkah 4\nOven selama 20-25 menit atau sampai matang atas bawah.\nLangkah 5\nSegera lumuri dengan gula halus selagi panas. Lakukan hingga habis. Setelah terbalut gula halus masukkan kedalam wadah gula dingin dan susu bubuk yang dicampur merata. Masukkan beberapa kue, lumuri/tutupi dengan gula dingin. Lakukan hingga selesai.\nLangkah 6\nMasukkan dalam wadah atau toples.\n', ''),
(27, 'Risoles', 'Risoles adalah makanan tradisional Indonesia yang berupa camilan. Risoles banyak dijumpai di warung-warung makan, pasar tradisional, dan toko kue di Indonesia. Karena rasa yang lezat dan kepraktisannya, risoles sering menjadi favorit di kalangan masyarakat Indonesia. Makanan ini terdiri dari kulit tepung terigu yang tipis dan diisi dengan campuran ragam bahan, seperti daging ayam atau sayuran yang dicampur dengan saus kental dan bumbu. Isian tersebut kemudian dibungkus dengan kulit tepung dan digulung seperti lumpia sebelum digoreng. Risoles memiliki tekstur kulit yang renyah dan isian yang lezat dengan kombinasi rasa gurih dan gurih. Setelah digoreng, risoles biasanya disajikan dengan saus atau sambal sebagai pelengkap. Makanan ini populer sebagai camilan di berbagai kesempatan, termasuk acara-acara khusus, perayaan, atau sekadar sebagai kudapan sehari-hari.', 'Bahan-bahan:\n1 buah pare\n2 butir telur\n1 sdt gula pasir\n2 sdm garam\nair secukupnya, untuk merebus pare\nsecukupnya wortel, potong dadu\nsecukupnya daun bawang, potong kecil2\n1 sdt Kaldu jamur tnpa MSG (saya pakai royco ayam)\n1 sdt lada bubuk\n2 sdm saos tiram\n3 siung bawang merah\nsecukupnya minyak goreng, untuk menumis\nbahan kulit:\n100 gr tepung serbaguna\n2 sdm tepung tapioka (kanji)\n1 butir telur\n1/4 sdt garam\n300 ml air\ntambahan:\n1 butir telur, untuk celupan kulit\ntepung panir\nCara Membuat:\nLangkah 1\nBersihkan pare, potong kecil2, remas2 dgn garam, cuci bersih. siapkan panci berisi air, masukkan pare dan tambah potongan dadu wortel dan daun bawang, rebus dengan menambahkan 1 sdt gula pasir.\nLangkah 2\nAngkat. tiriskan. lalu potong kecil-kecil bawang merah dan daun bawang. pecahkan 2 butir telur, kocok dalam wadah dgn menambahkan kaldu jamur& lada.\nLangkah 3\nPanaskan minyak dlm teflon, tumis bawang merah, daun bawang, & saos tiram sampai harum. masukkan pare. ratakan.\nLangkah 4\nMasukkan telur, ratakan dgn cara memutar teflon searah jarum jam. jangan lupa di balik supaya matang kedua sisi. angkat, tiriskan. dan potong kecil2 untuk isian risoles.\nLangkah 5\nMembuat kulit risoles : campur semua bahan kulit. aduk2 jangan sampai ada gumpalan.\nLangkah 6\nPanaskan sedikit minyak goreng, ambil 1 sendok sayur, goreng di atas teflon, ratakan. goreng sampai habis, sisakan sedikit utk lem.\nLangkah 7\nJika sudah selesai, isikan telur dadar pare. lem dengan sisa adonan kulit.\nLangkah 8\nCelup dalam telur, dan gulungkan ke tepung panir. lalu goreng, dengan api sedang.\nLangkah 9\nSajikan di atas piring dengan saos sambal/ mayonnaise. ', ''),
(28, 'Lanting', 'Lanting adalah makanan ringan sejenis kerupuk yang berbahan dasar singkong. Makanan yang berbentuk angka 8 ini merupakan makanan khas yang berasal dari Kebumen. Lanting biasanya digunakan sebagai oleh-oleh karena makanan ini tahan lama. Panganan ringan ini bisa menjadi favorit keluarga. Rasa renyah dan gurih dari lanting ini memang sangat khas. Namun saat ini mulai muncul aneka rasa, seperti asin, pedas, dan keju. Rasa khas singkong ini membuat lanting cocok sebagai camilan.\r\n', 'Bahan-bahan:\n1/4 singkong rebus\nSejumput garam (apabila singkong sudah asin, maka tidak perlu)\nSejumput ketumbar bubuk\nCara Membuat:\nLangkah 1\nTumbuk halus singkong, kemudian taburi garam dan ketumbar. Aduk sampai merata.\nLangkah 2\nJika dirasa sudah rata bumbunya. Kemudian bentuk memanjang kemudian rekatkan kedua ujungnya hingga membentuk bulat. Bisa juga dibentuk angka delapan.\nLangkah 3\nTata pada wadah agak berjarak supaya cepat kering. Kemudian jemur hingga kering di bawah matahari langsung ± 3 hari (menyesuaikan cuaca).\nLangkah 4\nSetelah kering, goreng dengan api sedang supaya tidak mudah gosong.', ''),
(29, 'Lumpia', 'Lumpia atau Lumpia Rebung adalah varian lumpia atau spring roll yang khas dari Semarang, Jawa Tengah. Hidangan ini terkenal karena menggunakan rebung sebagai salah satu bahan utamanya. Lumpia Rebung biasanya terdiri dari adonan kulit lumpia yang tipis yang diisi dengan campuran rebung, daging ayam cincang atau udang, tauge (kecambah), dan sejumlah bumbu rempah. Isian lumpia kemudian digulung dalam kulit lumpia dan kemudian digoreng hingga kulitnya menjadi renyah dan berwarna keemasan. Lumpia Rebung sering disajikan dengan saus kacang atau saus cabai untuk menambah cita rasa. Hidangan ini memiliki kombinasi rasa yang gurih, segar, dan sedikit pedas. Lumpia Rebung biasanya dijual di warung-warung makan atau pedagang kaki lima di Semarang dan sekitarnya. Hidangan ini menjadi pilihan yang populer di kalangan pecinta kuliner Indonesia karena cita rasanya yang lezat dan teksturnya yang renyah.\r\n', 'Bahan-bahan :\n250 gr rebung\n2 lbr Daun salam\n1 sdt garam\n15 kulit lumpia / kulit pangsit siap pakai\nsecukupnya Minyak goreng\nBahan Isi :\n10 gr Ebi rendam air panas haluskan\n50 gr Ayam cincang halus\n2 buah telur\n3 Sdm kecap manis\n1 Sdm kecap asin\n1 Sdm Saus tiram\n1 Sdm minyak wijen\n1 Batang daun bawang\nSecukupnya gula garam lada dan penyedap\nBumbu halus :\n5 siaung bawang merah\n3 siung bawang putih\n1 Ruas jari jahe\nBahan perekat :\n1 sdm tepung terigu\n20 ml air matang\nBumbu Saus Lumpia :\n100 ml air\n1 sdm kecap manis\n1 sdm kecap ikan\nSecukupnya gula, garam, lada dan penyedap\n1 sdt tepung maizena larutkan sedikit air\nCara Membuat:\nLangkah 1\nCuci bersih rebung sampai 3x, kemudian potong2 memanjang, rebus dengan garam dan daun salam\nLangkah 2\nAngkat tiriskan, rendam ebi dengan air panas ±15 menit, blender bumbu halus\nLangkah 3\nCincang ayam, peras ebi, haluskan.\n- Siapkan wajan, masukkan minyak\n- tumis daun bawang hingga harum\nLangkah 4\nMasukkan ayam aduk hingga ayam berubah warna\n- Tambahkan ebi dan bumbu halus\n- Masukkan telur di pinggir dan orak arik\nLangkah 5\nTambahkan kecap, saus tiram, kecap asin, minyak wijen, dan secukupnya garam gula lada penyedap, aduk hingga tercampur semua, koreksi rasa, jika sudah matang angkat sisihkan\nLangkah 6\nMembuat saus lumpia :\n- Didihkan air, tambahkan kecap, minyak ikan\n- Tambahkan larutan maizena, secukupnya gula garam lada dan penyedap\n- aduk hingga mengental, sisihkan\nLangkah 7\nAmbil 1 kulit lumpia, letakkan bahan isi di tepi kulit, lipat dan gulung,rekatkan dengan campuran bahan perekat.\nLangkah 8\nGoreng lumpia dengan api cenderung kecil biar tidak gosong, angkat dan tiriskan jika sudah golden brown\nLangkah 9\nHidangkan lumpia dengan daun bawang saus dan juga lombok rawit', '');
INSERT INTO `resep` (`resep_id`, `nama_resep`, `deskripsi_resep`, `bahan`, `gambar`) VALUES
(30, 'Putu Ayu', 'Putu Ayu adalah sejenis kue tradisional Indonesia yang memiliki bentuk bundar dan umumnya berwarna putih. Kue ini terbuat dari adonan beras ketan dan kelapa parut yang dicampur dengan kelapa muda dan gula kelapa. Adonan kemudian diletakkan dalam cetakan bundar kecil atau daun pisang dan dikukus hingga matang. Setelah matang, Putu Ayu biasanya memiliki lapisan kelapa parut di bagian luar yang memberikan tekstur kenyal dan serat pada kue. Rasa kue ini umumnya manis dengan sentuhan gurih dari kelapa. Putu Ayu sering dijadikan hidangan kudapan atau camilan dan sering dijual di pasar tradisional, warung kopi, atau toko kue di Indonesia. Selain sebagai cemilan sehari-hari, Putu Ayu juga sering dihidangkan pada acara-acara tertentu atau perayaan sebagai salah satu variasi kue tradisional Indonesia yang populer.\r\n', 'Bahan-bahan:\n250 / 300 gram kelapa parut yg muda & baru yah\n2 sdm tepung maizena\n1/2 sdt garam\n4 butir telur utuh\n240 gram gula pasir (15 sdm)\n1 sdt Vanilla bubuk\n1 sdt SP\n300 gram terigu protein sedang (me : serbaguna)\n2 sdm tepung tapioka\n1/2 sdt garam\n260 santan kental (2 saset santan instan campur air ya)\n1 sdm pasta pandan\n200 gram gula merah\nCara Membuat:\nLangkah 1\nSiapkan bahan2 terlebih dahulu\nLangkah 2\nKukus kelapa parut yg sudah ditambahkan tepung maizena & garam, selama kurleb 15 menit, jika sudah masukkan ke dlm Loyang yg sudah diolesi minyak, tekan2 pakai sendok agar padat yah, sisihkan\nLangkah 3\nMasukkan telur, gula putih, sp, vanilli, kocok hingga putih berjejak, jgn terlalu lama paling ±10 menit\nLangkah 4\nMatikan mixer, masukkan terigu, tep.tapioka, garam, sambil diayak, biar tidak menggumpal, terus diaduk lagi dengan mixer speed paling rendah, sampai rata\nLangkah 5\nBaru masukkan santan kental nya bertahap sambil terus diaduk\nLangkah 6\nKalau sudah tercampur rata, masukkan pasta pandan, aduk2 pakai spatula dengan teknik aduk balik, hingga warnanya tercampur ke semua adonan\nLangkah 7\nMasukkan ½ adonan ke dlm Loyang yg sudah dikasih kelapa tadi, pastikan kukusan sdh dipanaskan terlebih dahulu ya, kukus selama 10 menit, jgn lupa tutupnya kukusan pakai serbet/lap agar air tidak menetes ke kuenya\nLangkah 8\nSetelah 10mnt buka tutupnya, masukkan gula merah & sisa adonan ke dlm Loyang, tutup lagi & kukus selama 25 menit, tea tusuk ya mom..utk memastikan matang tidaknya, punyaku agak menggelembung lupa tdk dihentakkan Loyang\nLangkah 9\nJika sudah matang, biarkan kue agak dingin dulu, baru keluarkan dr Loyang...\nPutu Ayu pun siap disantap ', ''),
(31, 'Rendang', 'Rendang adalah hidangan daging yang berasal dari Minangkabau, Sumatra Barat, dan telah dikenal sebagai salah satu makanan tradisional Indonesia yang paling terkenal. Hidangan ini umumnya terbuat dari potongan daging sapi yang dimasak dalam santan dan bumbu rempah-rempah yang kaya, seperti serai, daun jeruk, cabai, bawang, jahe, dan kelapa parut. Proses memasak rendang memakan waktu yang cukup lama, di mana daging dimasak perlahan-lahan dalam santan hingga bumbu meresap dan meresahkan daging, serta menciptakan tekstur yang empuk dan kaya akan rasa. Rendang memiliki cita rasa yang unik, kombinasi dari rasa gurih, pedas, manis, dan rempah yang kaya. Rendang sering dianggap sebagai salah satu hidangan daging panggang terenak di dunia dan telah mendapatkan popularitas internasional. Hidangan ini biasanya disajikan pada acara-acara istimewa, perayaan, atau sebagai hidangan istimewa pada hari-hari tertentu.\r\n', 'Bahan-bahan:\n4 kg daging sapi\n4 Liter santan kental/ santan murni (kalau kelapa dari 16 butir kelapa) sy pakai 4 Liter santan instant\n8 L santan encer (bersihkan kemasan santan)\n1 kg cabe giling (1/2 kg cabe keriting, 1/2 kg cabe merah besar)\nBumbu Halus :\n800 gram / 80 siung bawang merah\n32 siung bawang putih\n20 gram jahe\n8 sdm ketumbar bubuk\n4 biji pala\n24 biji cengkeh\nBumbu Cemplung :\n4 bunga lawang\n25 biji kapulaga\n12 cm / 4 batang kayumanis\n8 batang sereh, memarkan\n8 lembar daun kunyit\n32 lembar daun jeruk\n1 pereket / 1 gunduk lengkuas, geprek\nMinyak untuk menumis\n4 sdm garam\nCara Membuat:\nLangkah 1\nSiapkan semua bahan,\nLangkah 2\nDan giling semua bumbu halus\nLangkah 3\nPanaskan minyak, tumis bumbu yang sudah dihaluskan, setelah wangi masukkan cabe giling, dan bumbu cemplung\nLangkah 4\nTumis hingga wangi\nMasukkan daging, tumis hingga bumbu meresap, masukkan santan kental\nLangkah 5\nDan masukkan juga santan encer\nMasak sampai mendidih, setelah mendidih kecilkan api\nLangkah 6\nMasak hingga mengental atau santannya menyusut, lebih lama lebih baik. Kemudian sajikan dengan nasi hangat', ''),
(32, 'Serabi Solo', 'Serabi Solo adalah sejenis kue tradisional Indonesia yang berasal dari Solo, Jawa Tengah. Makanan ini terbuat dari adonan berbahan dasar tepung beras, kelapa parut, gula kelapa, santan, dan sedikit garam. Adonan tersebut kemudian dipanggang atau dikukus hingga matang. Serabi Solo memiliki dua varian utama, yaitu serabi manis dan serabi asin. Serabi manis umumnya disajikan dengan taburan kelapa parut dan gula kelapa di atasnya, sementara serabi asin dapat dihidangkan dengan berbagai jenis saus, seperti saus kacang atau saus kecap. Keistimewaan Serabi Solo terletak pada teksturnya yang kenyal dan rasa yang lezat, serta aroma harum kelapa parut. Makanan ini sering dijual sebagai jajanan tradisional di pasar-pasar atau warung makan di Indonesia. Selain sebagai camilan sehari-hari, Serabi Solo juga sering dihidangkan pada acara-acara khusus dan perayaan tertentu.\r\n', 'Bahan-bahan:\n100 g Tepung beras\n1 sdm Terigu protein sedang\n350 ml Santan kental (saya pake 100 ml santan kental instan + air 250 ml)\n2 lembar Daun pandan, ikat simpul\n25 g Gula pasir\n1 sdt Ragi instan\n1/2 sdt Vanili bubuk\n1/4 sdt Baking soda\n1/4 sdt Garam\nCara Membuat:\nLangkah 1\nTuang santan & garam dalam panci, aduk rata. Masukkan daun pandan, masak hingga mendidih dengan api kecil sambil terus diaduk. Matikan api, ambil santan kental yang ada di bagian atas atau yang biasa disebut dengan areh ± 50 ml. Biarkan hingga santan dingin.\nLangkah 2\nCampur rata tepung beras, terigu, gula, ragi, vanili bubuk & baking soda dalam mangkok. Lalu tuang larutan santan tadi, aduk hingga rata. Tutup mangkok dengan serbet/plastik wrap & diamkan sekitar 1 jam.\nLangkah 3\nSetelah 1 jam, adonan akan berbuih.\nSiapkan wajan, oles dengan sedikit minyak. Panaskan dengan api kecil. Setelah panas, tuang 1 sendok sayur adonan sambil sedikit diratakan dengan punggung sendok.\nLangkah 4\nSetelah muncul gelembung², beri 1 sdm areh lalu beri topping. Tutup & masak hingga matang. Keluarkan adonan dari wajan, hati² ya supaya tidak hancur. Lakukan hingga adonan habis.\nLangkah 5\nTaruh di piring & sajikan ketika hangat', ''),
(33, 'Telur balado', 'Telur balado merupakan salah satu hidangan khas Minangkabau, Sumatra Barat. Hidangan ini umumnya terdiri dari telur yang direbus, digoreng, atau direbus setengah matang, yang kemudian disajikan dengan saus balado. Saus balado adalah saus pedas khas Indonesia yang terbuat dari cabai, bawang, tomat, dan bumbu-bumbu lainnya. Saus ini memberikan rasa pedas, manis, dan sedikit asam, menciptakan kombinasi cita rasa yang menggugah selera. Telur balado sering dihidangkan sebagai lauk pendamping nasi putih dan merupakan hidangan yang populer di seluruh Indonesia, terutama bagi mereka yang menyukai makanan pedas. Kelezatan telur balado juga sering membuatnya menjadi pilihan dalam masakan sehari-hari dan acara-acara khusus.\r\n', 'Bahan-bahan:\n3 butir Telur rebus\n10 buah Cabe kriting merah\n4 butir Bamer (Bawang merah)\n2 siung Baput (Bawang putih), saya skip\n1 buah Tomat\n1/2 sdt Garam\n2 biji Asam jawa; larutkan dalam 1 sdm Air, buang bijinya\nSecukupnya Minyak goreng\nCara Membuat:\nLangkah 1\nGoreng Telur sebentar hingga bagian luarnya kecoklatan. Angkat, kemudian tiriskan.\nLangkah 2\nGiling Cabe dan Garam menggunakan cobek, setengah halus tambahkan Bamer dan Tomat. Lalu giling lagi hingga halus. 📝 Noted:\nBalado khas Minang, menggiling bumbunya pakai cobek. Jangan pakai blender.\nLangkah 3\nMasukan cabe giling ke minyak sisa goreng telur tadi, lalu tambahkan air Asam. Aduk. Tes rasa. Masak hingga matang tanak. Kemudian masukan telur yang sudah di goreng. Aduk rata. Masak hingga bumbu meresap. Angkat.\nLangkah 4\nTelur Balado khas Minang pun siap disajikan. ', ''),
(34, 'Telur Dadar', 'Telur Dadar memiliki banyak vasiasi salah satunya yaitu telur dadar khas dari daerah Padang, Sumatra Barat. Telur dadar ini memiliki ciri khas rasa pedas dan gurih yang menggoda selera. Bahan utama dalam Telur Dadar Padang adalah telur yang dikocok dan dicampur dengan bumbu-bumbu khas, seperti cabai merah, bawang merah, bawang putih, kunyit, ketumbar, dan daun bawang. Campuran telur dan bumbu tersebut kemudian dipanaskan dalam wajan atau penggorengan hingga matang dan berbentuk dadar tipis. Telur dadar Padang sering dihidangkan sebagai lauk pendamping nasi putih dalam hidangan makanan Padang atau dikenal sebagai \"nasi Padang.\" Rasa gurih, pedas, dan rempah-rempah yang khas membuat Telur Dadar Padang menjadi hidangan yang populer di seluruh Indonesia. Hidangan ini sering dijumpai di restoran Padang dan warung makan tradisional yang menyajikan masakan khas Minangkabau.\r\n', 'Bahan-bahan :\n3 butir Telur Bebek\n5 sdm Kelapa Parut\n3 sdm Tepung Beras\n2 batang Daun Bawang, iris, saya skip, habis\n1 batang Seledri, iris\nBumbu halus :\n3 siung Bawang Merah\n2 siung Bawang Putih\n1 butir Kemiri\n1/4 sdt Ketumbar bubuk\n4 buah Cabai Merah Keriting\n1/4 sdt Kunyit bubuk\n1/2 sdt Lada bubuk\n1 sdt Garam\n1/2 sdt Kaldu bubuk\nCara Membuat:\nLangkah 1\nSangrai kelapa sampai sedikit kekuningan, sisihkan. Saya pakai kelapa bekas ayam bumbu.\nLangkah 2\nSiapkan wadah, pecahkan telur bebek, masukkan bumbu halus, tepung beras, kelapa sangrai, daun bawang & daun seledri, garam, lada bubuk, dan kaldu bubuk aduk rata\nLangkah 3\nPanaskan minyak (minyak jangan terlalu banyak & terlalu sedikit). Setelah minyak benar-benar panas tuang telur dan kecilkan api supaya telur tidak cepat gosong. Diamkan saja jangan diaduk-aduk. Setelah cukup kokoh balik telur dan diamkan kembali sampai matang.\nLangkah 4\nSetelah telur matang, tiriskan terlebih dahulu baru kemudian dipotong-potong. Telur dadar khas Padang siap disajikan. ', ''),
(35, 'Wajik', 'Wajik adalah salah satu makanan tradisional Indonesia yang terkenal. Makanan ini biasanya dibuat dari bahan dasar ketan yang direbus dan dicampur dengan kelapa parut serta gula merah. Wajik memiliki cita rasa manis dan kenyal dengan aroma khas kelapa parut. Makanan ini sering dihidangkan sebagai cemilan tradisional atau kue pada berbagai acara dan perayaan, seperti hari raya atau pernikahan. Keunikan dan kelezatan wajik membuatnya menjadi favorit di berbagai daerah di Indonesia, dan variasi resep dapat ditemukan tergantung pada tradisi lokal masing-masing.\r\n', 'Bahan-bahan:\n1/2 liter beras ketan,cuci bersih\n65 ml santan kental instan\n300 ml air\n200 gr gula merah,sisir\n1 sdm gula pasir\n1/2 sdt garam\n1 lembar daun pandan\nCara Membuat:\nLangkah 1\nDalam wajan campur gula merah, gula pasir,air,santan,daun pandan lalu rebus sampai gula larut dan mendidih.\nLangkah 2\nSetelah santan mendidih masukkan beras ketan masak sampai santan menyusut.\nLangkah 3\nPanaskan kukusan lalu kukus ketan selama 30menit.\nLangkah 4\nTuang ketan kedalam wadah yang sudah dialasi daun pisang/plastik,lalu ratakan dan padatkan. Diamkan sampai set.\nLangkah 5\nSetelah set lalu potong2 dengan pisau yang dilapisi plastik supaya tidak nempel. Siap dinikmati.', ''),
(71, 'Telur Dadar', 'e', 'e', 'gambar/telurdadar5.jpeg');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `user_id` int(11) NOT NULL,
  `username` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `role` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`user_id`, `username`, `name`, `role`, `password`) VALUES
(1, 'admin', 'Achmad Kahlil Gibran', 'admin', 'admin12345'),
(2, 'sSo12345', 'Adi Kristianto', 'user', 'sSosSo123'),
(3, 'cava1912', 'Achmad Kahlil Gibran', 'user', 'Indomiegoreng19'),
(4, 'test1', 'test', 'user', 'test1'),
(6, 'Kadaha', 'Akhmad Aditya Rachman', 'user', 'baksotanpatepung'),
(7, 'test2', 'test2', 'user', 'test2');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `user_id` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `name` varchar(100) DEFAULT NULL,
  `role` enum('user','admin') DEFAULT 'user',
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `bookmarks`
--
ALTER TABLE `bookmarks`
  ADD KEY `fk_user_id` (`user_id`);

--
-- Indexes for table `resep`
--
ALTER TABLE `resep`
  ADD PRIMARY KEY (`resep_id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`user_id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`user_id`),
  ADD UNIQUE KEY `username` (`username`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `resep`
--
ALTER TABLE `resep`
  MODIFY `resep_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=72;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `user_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `user_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `bookmarks`
--
ALTER TABLE `bookmarks`
  ADD CONSTRAINT `fk_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
